/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.marcusoliver.loan.tracker;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.time.*; 
/**
 *
 * @author marcu
 */
public class AddALoan extends javax.swing.JFrame {

    /**
     * Creates new form AddALoan
     */
    public AddALoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loanType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jbtnSubmit = new javax.swing.JButton();
        jbtnBackToAddTrack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        loanType.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car Loan", "House Loan", "Education Loan", "Business Loan" }));
        loanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeActionPerformed(evt);
            }
        });
        getContentPane().add(loanType);
        loanType.setBounds(600, 360, 460, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Type of Loan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(597, 320, 140, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Add a Loan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(79, 80, 290, 64);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Name of Borrower");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 200, 194, 32);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 240, 458, 62);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Amount Requested");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 320, 206, 32);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 360, 458, 62);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Due");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 200, 43, 32);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(600, 240, 458, 62);

        jbtnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSubmit);
        jbtnSubmit.setBounds(600, 440, 120, 39);

        jbtnBackToAddTrack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnBackToAddTrack.setText("Back");
        jbtnBackToAddTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackToAddTrackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBackToAddTrack);
        jbtnBackToAddTrack.setBounds(430, 440, 104, 39);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jeayan\\Pictures\\Blue and White Modern Company Meeting Zoom Virtual Background.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -14, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanTypeActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        // Get values from text fields
        ZoneId z = ZoneId.of("Asia/Manila");
        LocalDate today = LocalDate.now(z);
        String borrowerName = jTextField2.getText();
        double amountRequested = Double.parseDouble(jTextField1.getText());
        String dueDate = jTextField3.getText();
        String selectedLoanType = loanType.getSelectedItem().toString();
        String startDate = today.toString();
        
        
        InterestTrack interestTrack = new InterestTrack();
        interestTrack.updateTable(borrowerName, amountRequested, startDate, dueDate, selectedLoanType);

        // Create an instance of TrackAPayment and update the table with loan data
        TrackAPayment trackAPayment = new TrackAPayment();
        trackAPayment.updateTable(borrowerName, amountRequested, dueDate, selectedLoanType);

        // Show TrackAPayment frame
        trackAPayment.setVisible(true);
        dispose();

        JOptionPane.showMessageDialog(this, "Submitted!");
        
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    private void jbtnBackToAddTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackToAddTrackActionPerformed
        AddATrack at = new AddATrack();
        at.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnBackToAddTrackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddALoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddALoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddALoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddALoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddALoan al = new AddALoan();
             
                // Set the size of the JFrame to match the screen dimensions
                al.setExtendedState(JFrame.MAXIMIZED_BOTH);
                al.setLocationRelativeTo(null); // Cen ter the JFrame on the screen
                al.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnBackToAddTrack;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JComboBox<String> loanType;
    // End of variables declaration//GEN-END:variables
}
